parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ferdyrurka\:
        resource: '../src/'
        exclude:
            - '../src/YourFeed/Domain/Entity/'
            - '../src/YourFeed/Domain/Exception/'
            - '../src/YourFeed/Application/Command/'
            - '../src/Kernel.php'
