parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ferdyrurka\:
        resource: '../src/'
        exclude:
            - '../src/YourFeed/Domain/Entity/'
            - '../src/YourFeed/Domain/Exception/'
            - '../src/YourFeed/Application/Command/'
            - '../src/Kernel.php'

    Algolia\AlgoliaSearch\SearchClient:
        factory: ['@Ferdyrurka\YourFeed\Infrastructure\Search\Factory\AlgoliaFactory', 'create']
        arguments:
            - '%env(ALGOLIA_APP_ID)%'
            - '%env(ALGOLIA_API_KEY)%'
